[config]
single_click=1

[desktop]
wallpaper_mode=color
wallpaper_common=1
desktop_bg=#2f5f8f
desktop_fg=#ffffff
desktop_shadow=#000000
show_wm_menu=0
sort=mtime;ascending;
show_documents=1
show_trash=1
show_mounts=1
